steps:
  # Backend: Build the Docker image
  - name: 'gcr.io/cloud-builders/ubuntu'
    entrypoint: 'bash'
    # List all files in the current directory
    args:
      - '-c'
      - 'ls -la'
# Configure timeout
timeout: '1200s' # 20 minutes
