steps:
  # Test the backend 
    # Step 1: Run unit tests
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Running tests..."
        go test ./... -v
        echo "Tests completed."

  # Backend: Build the Docker image for the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', '${_GAR}/${_IMAGE}-backend:${_TAG}', '.' ]
    dir: 'backend'
  # Backend: Push the image to GAR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_GAR}/${_IMAGE}-backend:${_TAG}'

  # Deploy: Deploy the backend to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/${_IMAGE}-backend', '${_GAR}/${_IMAGE}-backend:${_TAG}']
    env:
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER}'
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CORE_REGION=${_REGION}'
      - 'CLOUDSDK_CORE_PROJECT=${PROJECT}'
    dir: 'manifests'
# Configure timeout
timeout: '1200s' # 20 minutes
