steps:
  # Backend: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${GAR}/${IMAGE}-backend:${TAG}'
      - './backend'
    dir: .
  
  # Frontend: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${GAR}/${IMAGE}-frontend:${TAG}'
      - './frontend'
    dir: .

  # Backend: Push the image to GAR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${GAR}/${IMAGE}-backend:${TAG}'

  # Frontend: Push the image to GAR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${GAR}/${IMAGE}-frontend:${TAG}'

# Define substitutions for dynamic variables
substitutions:
  _REGION: 'us-central1' # Default region (can be overridden)
  _GAR: 'us-central1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPO_NAME' # Replace with your GAR repo
  _IMAGE: 'online-shop'
  _TAG: 'latest'

# Configure timeout
timeout: '1200s' # 20 minutes
