apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop-backend
  template:
    metadata:
      labels:
        app: online-shop-backend
    spec:
      containers:
      - name: backend
        image: '${_GAR}/${_IMAGE}-backend:${_TAG}'
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
