# Namespace definition
apiVersion: v1
kind: Namespace
metadata:
  name: ginny

---
# ServiceAccount definition
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ginny-sa # Match this name with the pod's serviceAccountName
  namespace: ginny

---
# Pod definition
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: ginny
spec:
  serviceAccountName: ginny-sa # Match this name with the ServiceAccount's name
  containers:
  - name: test-pod
    image: google/cloud-sdk:slim
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 10Mi
