apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop-backend
  namespace: online-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop-backend
  template:
    metadata:
      labels:
        app: online-shop-backend
    spec:
      containers:
      - name: backend
        image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/YOUR_REPO_NAME/online-shop-backend:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
